version: "3.9"

services:
  whisper-asr:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: whisper-gpu-server
    container_name: whisper-asr

    ports:
      - "8010:8000"

    environment:
      DEFAULT_MODEL: "kiendt/PhoWhisper-large-ct2"
      CT2_DEVICE: "cuda"
      CT2_COMPUTE_TYPE: "float16"
      HF_HOME: "/root/.cache/huggingface"
      BE_BASE_URL: "http://localhost:5000"
      LOG_LEVEL: "INFO"
      TAGGER_BACKEND: "none"      
      TAGGER_MODEL: ""
      TAGGER_DEVICE: "cuda"

    volumes:
      - "E:/D/vnpt/quanLyNghiaTrang_1/whisper/.cache/huggingface:/root/.cache/huggingface"
      - "E:/D/vnpt/quanLyNghiaTrang_1/whisper/server/app.py:/app/app.py:ro"

    gpus: "all"

    restart: unless-stopped

    command:
      [
        "uvicorn",
        "app:app",
        "--host", "0.0.0.0",
        "--port", "8000",
        "--timeout-keep-alive", "120",
        "--log-level", "info",
        "--reload"
      ]

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 5
