version: "3.9"

services:
  whisper-asr:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: whisper-gpu-server
    container_name: whisper-asr
    ports:
      - "8010:8000"

    environment:
      DEFAULT_MODEL: "kiendt/PhoWhisper-large-ct2"
      CT2_DEVICE: "cuda"
      CT2_COMPUTE_TYPE: "float16"
      HF_HOME: "/root/.cache/huggingface"
      BE_BASE_URL: "http://localhost:5000"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"

    # Mount để code app.py luôn đồng bộ với máy thật
    volumes:
      # cache huggingface
      - "E:/D/vnpt/quanLyNghiaTrang_1/whisper/.cache/huggingface:/root/.cache/huggingface"
      # mount app.py từ host (khi bạn sửa thì container cũng cập nhật)
      - "E:/D/vnpt/quanLyNghiaTrang_1/whisper/server/app.py:/app/app.py:ro"

    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    command: [
      "uvicorn",
      "app:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--timeout-keep-alive", "120",
      "--log-level", "info"
    ]
